# Generated by Django 5.0.7 on 2024-07-27 07:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('offer', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('chapter', models.IntegerField(default=0)),
                ('overview', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=50)),
                ('chapters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default=list, size=None)),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=120)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('duration', models.IntegerField(default=0)),
                ('lessons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default=list, size=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_course', to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(to='course.faq'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('videoURL', models.CharField(max_length=120)),
                ('notesURL', models.CharField(max_length=120)),
                ('presentationURL', models.CharField(max_length=120)),
                ('codeURL', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('quizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default=list, size=None)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=120)),
                ('answer', models.IntegerField(default=0)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default=list, size=None)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
    ]
