# Generated by Django 5.1.2 on 2024-12-16 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('feedback', models.TextField(blank=True, default='', null=True)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
