# Generated by Django 5.1.2 on 2024-12-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
