# Generated by Django 5.2 on 2025-04-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.CharField(editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount', models.IntegerField(help_text='Discount percentage offered by the coupon')),
                ('expiry', models.DateField(help_text='Expiry date of the coupon')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Total quantity of coupons available', null=True)),
                ('used', models.IntegerField(default=0, help_text='Number of coupons used so far')),
                ('is_unlimited', models.BooleanField(default=False, help_text='Indicates if the coupon has unlimited usage')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the coupon is currently active')),
            ],
        ),
        migrations.DeleteModel(
            name='CuponeCode',
        ),
    ]
